apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
data:
  DB_USERNAME: "postgres"
  DB_NAME: "postgres"
  DB_HOST: "db-service-postgresql.default.svc.cluster.local"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_PASSWORD: "0FBXJVs9Xd"